#!/usr/bin/env python3
# SLATE Design Tokens — Auto-generated by token_propagator.py
# Source: design-tokens.json v3.1.0
# Generated: 2026-02-09T18:42:18Z | Author: Gemini
# WARNING: Do not edit manually — regenerate with: python slate/token_propagator.py
"""Auto-generated design token constants."""

VERSION = "3.1.0"
LOCKED = True

TOKEN_COLOR_PRIMARY_BASE = "#B85A3C"
TOKEN_COLOR_PRIMARY_LIGHT = "#D4785A"
TOKEN_COLOR_PRIMARY_DARK = "#8B4530"
TOKEN_COLOR_PRIMARY_CONTAINER_LIGHT = "#FFE4D9"
TOKEN_COLOR_PRIMARY_CONTAINER_DARK = "#5C2E1E"
TOKEN_COLOR_PRIMARY_ON_LIGHT = "#FFFFFF"
TOKEN_COLOR_PRIMARY_ON_DARK = "#2A1508"
TOKEN_COLOR_PRIMARY_ON_CONTAINER_LIGHT = "#3D1E10"
TOKEN_COLOR_PRIMARY_ON_CONTAINER_DARK = "#FFE4D9"
TOKEN_COLOR_BLUEPRINT_BG = "#0D1B2A"
TOKEN_COLOR_BLUEPRINT_GRID = "#1B3A4B"
TOKEN_COLOR_BLUEPRINT_ACCENT = "#98C1D9"
TOKEN_COLOR_BLUEPRINT_NODE = "#E0FBFC"
TOKEN_COLOR_SURFACE_BASE_LIGHT = "#FBF8F6"
TOKEN_COLOR_SURFACE_BASE_DARK = "#1A1816"
TOKEN_COLOR_SURFACE_VARIANT_LIGHT = "#F0EBE7"
TOKEN_COLOR_SURFACE_VARIANT_DARK = "#2A2624"
TOKEN_COLOR_SURFACE_ON_LIGHT = "#1C1B1A"
TOKEN_COLOR_SURFACE_ON_DARK = "#E8E2DE"
TOKEN_COLOR_SURFACE_ON_VARIANT_LIGHT = "#4D4845"
TOKEN_COLOR_SURFACE_ON_VARIANT_DARK = "#CAC4BF"
TOKEN_COLOR_OUTLINE_BASE_LIGHT = "#7D7873"
TOKEN_COLOR_OUTLINE_BASE_DARK = "#968F8A"
TOKEN_COLOR_OUTLINE_VARIANT_LIGHT = "#CFC8C3"
TOKEN_COLOR_OUTLINE_VARIANT_DARK = "#4D4845"
TOKEN_COLOR_STATUS_ACTIVE = "#4CAF50"
TOKEN_COLOR_STATUS_PENDING = "#FF9800"
TOKEN_COLOR_STATUS_ERROR = "#F44336"
TOKEN_COLOR_STATUS_INFO = "#2196F3"
TOKEN_COLOR_STATUS_INACTIVE = "#6B7280"
TOKEN_COLOR_STEP_ACTIVE = "#3B82F6"
TOKEN_COLOR_STEP_COMPLETE = "#22C55E"
TOKEN_COLOR_STEP_PENDING = "#9CA3AF"
TOKEN_COLOR_STEP_ERROR = "#EF4444"
TOKEN_COLOR_WATCHMAKER_COPPER = "#B87333"
TOKEN_COLOR_WATCHMAKER_BRASS = "#C9A959"
TOKEN_COLOR_WATCHMAKER_STEEL = "#71797E"
TOKEN_COLOR_WATCHMAKER_GOLD = "#DAA520"
TOKEN_COLOR_WATCHMAKER_JEWEL_RUBY = "#E0115F"
TOKEN_COLOR_WATCHMAKER_JEWEL_EMERALD = "#50C878"
TOKEN_COLOR_WATCHMAKER_JEWEL_SAPPHIRE = "#0F52BA"
TOKEN_COLOR_GLASSMORPHISM_GLASS_BG = "rgba(255,255,255,0.05)"
TOKEN_COLOR_GLASSMORPHISM_GLASS_BORDER = "rgba(255,255,255,0.1)"
TOKEN_COLOR_GLASSMORPHISM_GLASS_SHINE = "rgba(255,255,255,0.08)"
TOKEN_COLOR_GLASSMORPHISM_GLASS_BLUR = "12px"
TOKEN_TYPOGRAPHY_DISPLAY_FAMILY = "'Styrene A', 'Inter Tight', system-ui, sans-serif"
TOKEN_TYPOGRAPHY_DISPLAY_FALLBACK = "system-ui, sans-serif"
TOKEN_TYPOGRAPHY_BODY_FAMILY = "'Tiempos Text', 'Georgia', serif"
TOKEN_TYPOGRAPHY_BODY_FALLBACK = "Georgia, serif"
TOKEN_TYPOGRAPHY_MONO_FAMILY = "'Cascadia Code', 'JetBrains Mono', 'Consolas', monospace"
TOKEN_TYPOGRAPHY_MONO_FALLBACK = "'Consolas', monospace"
TOKEN_TYPOGRAPHY_SCALE_DISPLAY_LARGE_SIZE = "57px"
TOKEN_TYPOGRAPHY_SCALE_DISPLAY_LARGE_WEIGHT = 400
TOKEN_TYPOGRAPHY_SCALE_DISPLAY_LARGE_LINE_HEIGHT = "64px"
TOKEN_TYPOGRAPHY_SCALE_DISPLAY_MEDIUM_SIZE = "45px"
TOKEN_TYPOGRAPHY_SCALE_DISPLAY_MEDIUM_WEIGHT = 400
TOKEN_TYPOGRAPHY_SCALE_DISPLAY_MEDIUM_LINE_HEIGHT = "52px"
TOKEN_TYPOGRAPHY_SCALE_DISPLAY_SMALL_SIZE = "36px"
TOKEN_TYPOGRAPHY_SCALE_DISPLAY_SMALL_WEIGHT = 400
TOKEN_TYPOGRAPHY_SCALE_DISPLAY_SMALL_LINE_HEIGHT = "44px"
TOKEN_TYPOGRAPHY_SCALE_HEADLINE_LARGE_SIZE = "32px"
TOKEN_TYPOGRAPHY_SCALE_HEADLINE_LARGE_WEIGHT = 400
TOKEN_TYPOGRAPHY_SCALE_HEADLINE_LARGE_LINE_HEIGHT = "40px"
TOKEN_TYPOGRAPHY_SCALE_HEADLINE_MEDIUM_SIZE = "28px"
TOKEN_TYPOGRAPHY_SCALE_HEADLINE_MEDIUM_WEIGHT = 400
TOKEN_TYPOGRAPHY_SCALE_HEADLINE_MEDIUM_LINE_HEIGHT = "36px"
TOKEN_TYPOGRAPHY_SCALE_HEADLINE_SMALL_SIZE = "24px"
TOKEN_TYPOGRAPHY_SCALE_HEADLINE_SMALL_WEIGHT = 400
TOKEN_TYPOGRAPHY_SCALE_HEADLINE_SMALL_LINE_HEIGHT = "32px"
TOKEN_TYPOGRAPHY_SCALE_TITLE_LARGE_SIZE = "22px"
TOKEN_TYPOGRAPHY_SCALE_TITLE_LARGE_WEIGHT = 500
TOKEN_TYPOGRAPHY_SCALE_TITLE_LARGE_LINE_HEIGHT = "28px"
TOKEN_TYPOGRAPHY_SCALE_TITLE_MEDIUM_SIZE = "16px"
TOKEN_TYPOGRAPHY_SCALE_TITLE_MEDIUM_WEIGHT = 500
TOKEN_TYPOGRAPHY_SCALE_TITLE_MEDIUM_LINE_HEIGHT = "24px"
TOKEN_TYPOGRAPHY_SCALE_TITLE_SMALL_SIZE = "14px"
TOKEN_TYPOGRAPHY_SCALE_TITLE_SMALL_WEIGHT = 500
TOKEN_TYPOGRAPHY_SCALE_TITLE_SMALL_LINE_HEIGHT = "20px"
TOKEN_TYPOGRAPHY_SCALE_BODY_LARGE_SIZE = "16px"
TOKEN_TYPOGRAPHY_SCALE_BODY_LARGE_WEIGHT = 400
TOKEN_TYPOGRAPHY_SCALE_BODY_LARGE_LINE_HEIGHT = "24px"
TOKEN_TYPOGRAPHY_SCALE_BODY_MEDIUM_SIZE = "14px"
TOKEN_TYPOGRAPHY_SCALE_BODY_MEDIUM_WEIGHT = 400
TOKEN_TYPOGRAPHY_SCALE_BODY_MEDIUM_LINE_HEIGHT = "20px"
TOKEN_TYPOGRAPHY_SCALE_BODY_SMALL_SIZE = "12px"
TOKEN_TYPOGRAPHY_SCALE_BODY_SMALL_WEIGHT = 400
TOKEN_TYPOGRAPHY_SCALE_BODY_SMALL_LINE_HEIGHT = "16px"
TOKEN_TYPOGRAPHY_SCALE_LABEL_LARGE_SIZE = "14px"
TOKEN_TYPOGRAPHY_SCALE_LABEL_LARGE_WEIGHT = 500
TOKEN_TYPOGRAPHY_SCALE_LABEL_LARGE_LINE_HEIGHT = "20px"
TOKEN_TYPOGRAPHY_SCALE_LABEL_MEDIUM_SIZE = "12px"
TOKEN_TYPOGRAPHY_SCALE_LABEL_MEDIUM_WEIGHT = 500
TOKEN_TYPOGRAPHY_SCALE_LABEL_MEDIUM_LINE_HEIGHT = "16px"
TOKEN_TYPOGRAPHY_SCALE_LABEL_SMALL_SIZE = "11px"
TOKEN_TYPOGRAPHY_SCALE_LABEL_SMALL_WEIGHT = 500
TOKEN_TYPOGRAPHY_SCALE_LABEL_SMALL_LINE_HEIGHT = "16px"
TOKEN_SPACING_0 = "0"
TOKEN_SPACING_XS = "4px"
TOKEN_SPACING_SM = "8px"
TOKEN_SPACING_MD = "16px"
TOKEN_SPACING_LG = "24px"
TOKEN_SPACING_XL = "32px"
TOKEN_SPACING_2XL = "48px"
TOKEN_SPACING_3XL = "64px"
TOKEN_RADIUS_NONE = "0"
TOKEN_RADIUS_XS = "4px"
TOKEN_RADIUS_SM = "8px"
TOKEN_RADIUS_MD = "12px"
TOKEN_RADIUS_LG = "16px"
TOKEN_RADIUS_XL = "24px"
TOKEN_RADIUS_2XL = "32px"
TOKEN_RADIUS_FULL = "9999px"
TOKEN_ELEVATION_0 = "none"
TOKEN_ELEVATION_1 = "0 1px 2px rgba(0,0,0,0.05), 0 1px 3px rgba(0,0,0,0.1)"
TOKEN_ELEVATION_2 = "0 2px 4px rgba(0,0,0,0.05), 0 4px 8px rgba(0,0,0,0.1)"
TOKEN_ELEVATION_3 = "0 4px 8px rgba(0,0,0,0.08), 0 8px 16px rgba(0,0,0,0.12)"
TOKEN_ELEVATION_4 = "0 8px 16px rgba(0,0,0,0.1), 0 16px 32px rgba(0,0,0,0.15)"
TOKEN_ELEVATION_5 = "0 16px 32px rgba(0,0,0,0.12), 0 32px 64px rgba(0,0,0,0.18)"
TOKEN_STATE_HOVER = 0.08
TOKEN_STATE_FOCUS = 0.12
TOKEN_STATE_PRESSED = 0.12
TOKEN_STATE_DRAGGED = 0.16
TOKEN_STATE_DISABLED = 0.38
TOKEN_MOTION_EASING_STANDARD = "cubic-bezier(0.4, 0, 0.2, 1)"
TOKEN_MOTION_EASING_DECELERATE = "cubic-bezier(0, 0, 0.2, 1)"
TOKEN_MOTION_EASING_ACCELERATE = "cubic-bezier(0.4, 0, 1, 1)"
TOKEN_MOTION_EASING_SPRING = "cubic-bezier(0.34, 1.56, 0.64, 1)"
TOKEN_MOTION_EASING_EXPO_OUT = "cubic-bezier(0.16, 1, 0.3, 1)"
TOKEN_MOTION_DURATION_INSTANT = "50ms"
TOKEN_MOTION_DURATION_FAST = "150ms"
TOKEN_MOTION_DURATION_NORMAL = "250ms"
TOKEN_MOTION_DURATION_SLOW = "400ms"
TOKEN_MOTION_DURATION_GLACIAL = "600ms"
TOKEN_MOTION_DURATION_AMBIENT = "3000ms"
TOKEN_MOTION_STAGGER_FAST = "30ms"
TOKEN_MOTION_STAGGER_NORMAL = "50ms"
TOKEN_MOTION_STAGGER_SLOW = "80ms"

TOKENS = {
  "color": {
    "primary": {
      "base": "#B85A3C",
      "light": "#D4785A",
      "dark": "#8B4530",
      "container": {
        "light": "#FFE4D9",
        "dark": "#5C2E1E"
      },
      "on": {
        "light": "#FFFFFF",
        "dark": "#2A1508"
      },
      "on-container": {
        "light": "#3D1E10",
        "dark": "#FFE4D9"
      }
    },
    "blueprint": {
      "bg": "#0D1B2A",
      "grid": "#1B3A4B",
      "accent": "#98C1D9",
      "node": "#E0FBFC"
    },
    "surface": {
      "base": {
        "light": "#FBF8F6",
        "dark": "#1A1816"
      },
      "variant": {
        "light": "#F0EBE7",
        "dark": "#2A2624"
      },
      "on": {
        "light": "#1C1B1A",
        "dark": "#E8E2DE"
      },
      "on-variant": {
        "light": "#4D4845",
        "dark": "#CAC4BF"
      }
    },
    "outline": {
      "base": {
        "light": "#7D7873",
        "dark": "#968F8A"
      },
      "variant": {
        "light": "#CFC8C3",
        "dark": "#4D4845"
      }
    },
    "status": {
      "active": "#4CAF50",
      "pending": "#FF9800",
      "error": "#F44336",
      "info": "#2196F3",
      "inactive": "#6B7280"
    },
    "step": {
      "active": "#3B82F6",
      "complete": "#22C55E",
      "pending": "#9CA3AF",
      "error": "#EF4444"
    },
    "watchmaker": {
      "copper": "#B87333",
      "brass": "#C9A959",
      "steel": "#71797E",
      "gold": "#DAA520",
      "jewel-ruby": "#E0115F",
      "jewel-emerald": "#50C878",
      "jewel-sapphire": "#0F52BA"
    },
    "glassmorphism": {
      "glass-bg": "rgba(255,255,255,0.05)",
      "glass-border": "rgba(255,255,255,0.1)",
      "glass-shine": "rgba(255,255,255,0.08)",
      "glass-blur": "12px"
    }
  },
  "typography": {
    "display": {
      "family": "'Styrene A', 'Inter Tight', system-ui, sans-serif",
      "fallback": "system-ui, sans-serif"
    },
    "body": {
      "family": "'Tiempos Text', 'Georgia', serif",
      "fallback": "Georgia, serif"
    },
    "mono": {
      "family": "'Cascadia Code', 'JetBrains Mono', 'Consolas', monospace",
      "fallback": "'Consolas', monospace"
    },
    "scale": {
      "display-large": {
        "size": "57px",
        "weight": 400,
        "line-height": "64px"
      },
      "display-medium": {
        "size": "45px",
        "weight": 400,
        "line-height": "52px"
      },
      "display-small": {
        "size": "36px",
        "weight": 400,
        "line-height": "44px"
      },
      "headline-large": {
        "size": "32px",
        "weight": 400,
        "line-height": "40px"
      },
      "headline-medium": {
        "size": "28px",
        "weight": 400,
        "line-height": "36px"
      },
      "headline-small": {
        "size": "24px",
        "weight": 400,
        "line-height": "32px"
      },
      "title-large": {
        "size": "22px",
        "weight": 500,
        "line-height": "28px"
      },
      "title-medium": {
        "size": "16px",
        "weight": 500,
        "line-height": "24px"
      },
      "title-small": {
        "size": "14px",
        "weight": 500,
        "line-height": "20px"
      },
      "body-large": {
        "size": "16px",
        "weight": 400,
        "line-height": "24px"
      },
      "body-medium": {
        "size": "14px",
        "weight": 400,
        "line-height": "20px"
      },
      "body-small": {
        "size": "12px",
        "weight": 400,
        "line-height": "16px"
      },
      "label-large": {
        "size": "14px",
        "weight": 500,
        "line-height": "20px"
      },
      "label-medium": {
        "size": "12px",
        "weight": 500,
        "line-height": "16px"
      },
      "label-small": {
        "size": "11px",
        "weight": 500,
        "line-height": "16px"
      }
    }
  },
  "spacing": {
    "0": "0",
    "xs": "4px",
    "sm": "8px",
    "md": "16px",
    "lg": "24px",
    "xl": "32px",
    "2xl": "48px",
    "3xl": "64px"
  },
  "radius": {
    "none": "0",
    "xs": "4px",
    "sm": "8px",
    "md": "12px",
    "lg": "16px",
    "xl": "24px",
    "2xl": "32px",
    "full": "9999px"
  },
  "elevation": {
    "0": "none",
    "1": "0 1px 2px rgba(0,0,0,0.05), 0 1px 3px rgba(0,0,0,0.1)",
    "2": "0 2px 4px rgba(0,0,0,0.05), 0 4px 8px rgba(0,0,0,0.1)",
    "3": "0 4px 8px rgba(0,0,0,0.08), 0 8px 16px rgba(0,0,0,0.12)",
    "4": "0 8px 16px rgba(0,0,0,0.1), 0 16px 32px rgba(0,0,0,0.15)",
    "5": "0 16px 32px rgba(0,0,0,0.12), 0 32px 64px rgba(0,0,0,0.18)"
  },
  "state": {
    "hover": 0.08,
    "focus": 0.12,
    "pressed": 0.12,
    "dragged": 0.16,
    "disabled": 0.38
  },
  "motion": {
    "easing": {
      "standard": "cubic-bezier(0.4, 0, 0.2, 1)",
      "decelerate": "cubic-bezier(0, 0, 0.2, 1)",
      "accelerate": "cubic-bezier(0.4, 0, 1, 1)",
      "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      "expo-out": "cubic-bezier(0.16, 1, 0.3, 1)"
    },
    "duration": {
      "instant": "50ms",
      "fast": "150ms",
      "normal": "250ms",
      "slow": "400ms",
      "glacial": "600ms",
      "ambient": "3000ms"
    },
    "stagger": {
      "fast": "30ms",
      "normal": "50ms",
      "slow": "80ms"
    }
  }
}
