# 
# SLATE GitHub Labels
# Author: COPILOT | Created: 2026-02-06T14:00:00Z
# Synced by .github/workflows/label-sync.yml
# 

# Priority
- name: 'priority: critical'
  color: 'b60205'
  description: 'Must be resolved immediately'
- name: 'priority: high'
  color: 'd93f0b'
  description: 'Should be resolved soon'
- name: 'priority: medium'
  color: 'fbca04'
  description: 'Normal priority'
- name: 'priority: low'
  color: '0e8a16'
  description: 'Nice to have'

# Type
- name: 'type: bug'
  color: 'd73a4a'
  description: 'Something is not working'
- name: 'type: feature'
  color: 'a2eeef'
  description: 'New feature or enhancement'
- name: 'type: refactor'
  color: 'e4e669'
  description: 'Code improvement without behavior change'
- name: 'type: docs'
  color: '0075ca'
  description: 'Documentation improvements'
- name: 'type: test'
  color: 'bfd4f2'
  description: 'Test improvements or additions'
- name: 'type: ci'
  color: 'c5def5'
  description: 'CI/CD pipeline changes'
- name: 'type: security'
  color: 'e11d48'
  description: 'Security-related changes'

# Component
- name: 'component: sdk'
  color: '5319e7'
  description: 'slate SDK'
- name: 'component: dashboard'
  color: '006b75'
  description: 'Dashboard server'
- name: 'component: agents'
  color: '1d76db'
  description: 'ALPHA/BETA/GAMMA/DELTA agents'
- name: 'component: ml'
  color: 'f9d0c4'
  description: 'ML training pipeline'
- name: 'component: tech-tree'
  color: '7057ff'
  description: 'Tech tree system'

# Agent
- name: 'agent: alpha'
  color: 'e6b800'
  description: 'ALPHA agent (coding/GPU)'
- name: 'agent: beta'
  color: '00b0d8'
  description: 'BETA agent (testing/GPU)'
- name: 'agent: gamma'
  color: '00b894'
  description: 'GAMMA agent (planning/CPU)'
- name: 'agent: delta'
  color: 'a29bfe'
  description: 'DELTA agent (external/Claude/Copilot)'

# Status
- name: 'status: in-progress'
  color: 'ededed'
  description: 'Currently being worked on'
- name: 'status: blocked'
  color: 'b60205'
  description: 'Blocked by external dependency'
- name: 'status: needs-review'
  color: 'fbca04'
  description: 'Needs code review'

# Meta
- name: 'stale'
  color: 'ffffff'
  description: 'No recent activity'
- name: 'pinned'
  color: '006b75'
  description: 'Exempt from stale bot'
- name: 'dependencies'
  color: '0366d6'
  description: 'Dependency updates'
- name: 'python'
  color: '3572A5'
  description: 'Python related'
- name: 'automated'
  color: 'ededed'
  description: 'Created by automation'
- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'
- name: 'do-not-close'
  color: 'b60205'
  description: 'Exempt from auto-close'
